# Generated by Django 5.0.4 on 2024-04-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_processed_rasa', models.BooleanField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('answer_by', models.TextField(blank=True, choices=[(0, 'observer'), (1, 'rasa')], null=True)),
                ('is_rasa_can_solve', models.BooleanField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('sent_to', models.TextField(blank=True, choices=[(0, 'rasa'), (1, 'gpt')], null=True)),
                ('gpt_answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('username', models.TextField()),
                ('tg_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
