# Generated by Django 5.0.4 on 2024-04-27 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_message_tg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='tg_id',
            new_name='user_id',
        ),
    ]
