# Generated by Django 5.0.4 on 2024-04-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_rename_tg_id_chat_usertg_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='answer_by',
            field=models.TextField(blank=True, choices=[('observer', 'observer'), ('rasa', 'rasa'), ('student', 'student')], null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_to',
            field=models.TextField(blank=True, choices=[('rasa', 'rasa'), ('gpt', 'gpt')], null=True),
        ),
    ]
