# Generated by Django 5.0.4 on 2024-04-27 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_student_lastname_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='on_message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.message'),
            preserve_default=False,
        ),
    ]
