# Generated by Django 5.0.4 on 2024-04-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_message_answer_by_alter_message_sent_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
